meta_product_name: "AudricWebDev"
meta_title: "AudricWebDev - Developpeur Web"
meta_description: "Developpeur Web Lyonnais et alentours"
meta_image: "logo.png" # should exist in `app/assets/images/`
twitter_account: "@product_twitter_account"   # required for Twitter Cards
